#!/usr/bin/env node

var sys = require('sys')
,node3p = require('./lib/node3p');

sys.puts('Node3p - An Amazon MP3 downloader.');

var n3p = new node3p.Node3p(process.argv[2]);
n3p.on('end',  function(files) {
	    sys.puts('All files downloaded.');
	  });
n3p.parse(process.argv[3]);